/**
 * main.pages.tsx
 *
 * Client-only entry point for GitHub Pages static deploy.
 * Uses @tanstack/react-router (NOT @tanstack/react-start),
 * so no SSR hydration / "Invariant failed" issues.
 */
import React from "react";
import ReactDOM from "react-dom/client";
import { RouterProvider, createRouter, createHashHistory } from "@tanstack/react-router";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
// routeTree.pages.gen.ts is generated by TanStackRouterVite in vite.pages.config.ts
// (no ssr:true declaration — pure client router)
import { routeTree } from "./routeTree.pages.gen";
import "./styles.css";

const queryClient = new QueryClient({
  defaultOptions: { queries: { staleTime: 60_000, retry: 1 } },
});

const router = createRouter({
  routeTree,
  context: { queryClient },
  defaultPreloadStaleTime: 0,
  history: createHashHistory(),
});

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </React.StrictMode>,
);
